import { describe, it, expect, vi, beforeEach } from 'vitest';
import request from 'supertest';

// Mock googleapis so no real OAuth client / network is involved.
// getToken is controllable per-test via the exported mock.
const getTokenMock = vi.fn();
const generateAuthUrlMock = vi.fn(
  (opts: { state?: string }) =>
    `https://accounts.google.com/o/oauth2/v2/auth?state=${opts.state ?? ''}`,
);

vi.mock('googleapis', () => ({
  google: {
    auth: {
      OAuth2: class {
        generateAuthUrl = generateAuthUrlMock;
        getToken = getTokenMock;
      },
    },
  },
}));

// Import after the mock is registered.
const { createApp } = await import('../app.js');

const FRONTEND = 'http://localhost:4200';

/**
 * Drives /auth/start to register a valid OAuth state on the server, then
 * returns that state so the callback's state check can pass.
 */
async function obtainValidState(app: ReturnType<typeof createApp>): Promise<string> {
  const res = await request(app).get('/auth/start');
  const location = res.headers['location'] as string;
  const state = new URL(location).searchParams.get('state');
  if (!state) throw new Error('No state generated by /auth/start');
  return state;
}

describe('GET /auth/callback error paths', () => {
  let app: ReturnType<typeof createApp>;

  beforeEach(() => {
    getTokenMock.mockReset();
    app = createApp();
  });

  it('redirects to the frontend with access_denied when the user declines consent', async () => {
    const res = await request(app).get('/auth/callback').query({ error: 'access_denied' });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=access_denied`);
    expect(res.headers['content-type'] ?? '').not.toContain('application/json');
  });

  it('redirects with invalid_state when the state is unknown', async () => {
    const res = await request(app)
      .get('/auth/callback')
      .query({ code: 'some-code', state: 'never-issued-state' });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=invalid_state`);
  });

  it('redirects with token_exchange_failed when the token exchange throws', async () => {
    getTokenMock.mockRejectedValueOnce(new Error('invalid_grant: secret detail'));
    const state = await obtainValidState(app);

    const res = await request(app)
      .get('/auth/callback')
      .query({ code: 'some-code', state });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=token_exchange_failed`);
    // Internal exception details must not leak into the redirect URL.
    expect(res.headers['location']).not.toContain('secret detail');
  });

  it('redirects with auth_failed when no code is provided', async () => {
    const res = await request(app).get('/auth/callback');

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=auth_failed`);
  });
});
