import { describe, it, expect, vi, beforeEach } from 'vitest';
import request from 'supertest';
import type TestAgent from 'supertest/lib/agent.js';

// Mock googleapis so no real OAuth client / network is involved.
// getToken is controllable per-test via the exported mock.
const getTokenMock = vi.fn();
const generateAuthUrlMock = vi.fn(
  (opts: { state?: string }) =>
    `https://accounts.google.com/o/oauth2/v2/auth?state=${opts.state ?? ''}`,
);

vi.mock('googleapis', () => ({
  google: {
    auth: {
      OAuth2: class {
        generateAuthUrl = generateAuthUrlMock;
        getToken = getTokenMock;
      },
    },
  },
}));

// Import after the mock is registered.
const { createApp } = await import('../app.js');

const FRONTEND = 'http://localhost:4200';

/** Extracts a cookie value from a response's Set-Cookie headers, or null. */
function cookieFromResponse(res: request.Response, name: string): string | null {
  const setCookies = ([] as string[]).concat(res.headers['set-cookie'] ?? []);
  for (const cookie of setCookies) {
    const match = cookie.match(new RegExp(`^${name}=([^;]*)`));
    if (match) return decodeURIComponent(match[1]);
  }
  return null;
}

/**
 * Drives /auth/start on the given agent (cookie jar!) so the OAuth state is
 * registered against the agent's session, then returns that state. The state
 * is session-bound, so the same agent must be used for the callback.
 */
async function obtainValidState(agent: TestAgent): Promise<string> {
  const res = await agent.get('/auth/start');
  const location = res.headers['location'] as string;
  const state = new URL(location).searchParams.get('state');
  if (!state) throw new Error('No state generated by /auth/start');
  return state;
}

describe('GET /auth/callback error paths', () => {
  let app: ReturnType<typeof createApp>;

  beforeEach(() => {
    getTokenMock.mockReset();
    app = createApp();
  });

  it('redirects to the frontend with access_denied when the user declines consent', async () => {
    const res = await request(app).get('/auth/callback').query({ error: 'access_denied' });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=access_denied`);
    expect(res.headers['content-type'] ?? '').not.toContain('application/json');
  });

  it('redirects with invalid_state when the state is unknown', async () => {
    const res = await request(app)
      .get('/auth/callback')
      .query({ code: 'some-code', state: 'never-issued-state' });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=invalid_state`);
  });

  it('redirects with token_exchange_failed when the token exchange throws', async () => {
    getTokenMock.mockRejectedValueOnce(new Error('invalid_grant: secret detail'));
    const agent = request.agent(app);
    const state = await obtainValidState(agent);

    const res = await agent.get('/auth/callback').query({ code: 'some-code', state });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=token_exchange_failed`);
    // Internal exception details must not leak into the redirect URL.
    expect(res.headers['location']).not.toContain('secret detail');
  });

  it('redirects with auth_failed when no code is provided', async () => {
    const res = await request(app).get('/auth/callback');

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(`${FRONTEND}/?auth_error=auth_failed`);
  });
});

describe('OAuth state is bound to the initiating session', () => {
  let app: ReturnType<typeof createApp>;

  beforeEach(() => {
    getTokenMock.mockReset();
    getTokenMock.mockResolvedValue({ tokens: { access_token: 'test-access-token' } });
    app = createApp();
  });

  it('accepts the callback from the same session that started the flow', async () => {
    const agent = request.agent(app);
    const state = await obtainValidState(agent);

    const res = await agent.get('/auth/callback').query({ code: 'some-code', state });

    expect(res.status).toBe(302);
    expect(res.headers['location']).toBe(FRONTEND);

    const status = await agent.get('/auth/status');
    expect(status.body).toEqual({ authenticated: true });
  });

  it('rejects a valid state presented by a different session (login CSRF)', async () => {
    const victimAgent = request.agent(app);
    const state = await obtainValidState(victimAgent);

    // Attacker has no (or a different) session cookie but knows the state.
    const attackerRes = await request(app)
      .get('/auth/callback')
      .query({ code: 'some-code', state });

    expect(attackerRes.status).toBe(302);
    expect(attackerRes.headers['location']).toBe(`${FRONTEND}/?auth_error=invalid_state`);
    expect(getTokenMock).not.toHaveBeenCalled();
  });
});

describe('XSRF token rotation', () => {
  let app: ReturnType<typeof createApp>;

  beforeEach(() => {
    getTokenMock.mockReset();
    getTokenMock.mockResolvedValue({ tokens: { access_token: 'test-access-token' } });
    app = createApp();
  });

  it('rotates the XSRF-TOKEN cookie on successful login callback', async () => {
    const agent = request.agent(app);
    const startRes = await agent.get('/auth/start');
    const preLoginToken = cookieFromResponse(startRes, 'XSRF-TOKEN');
    expect(preLoginToken).toBeTruthy();

    const state = new URL(startRes.headers['location']).searchParams.get('state')!;
    const callbackRes = await agent.get('/auth/callback').query({ code: 'some-code', state });

    const postLoginToken = cookieFromResponse(callbackRes, 'XSRF-TOKEN');
    expect(postLoginToken).toBeTruthy();
    expect(postLoginToken).not.toBe(preLoginToken);
  });

  it('rotates the XSRF-TOKEN cookie on logout', async () => {
    const agent = request.agent(app);
    const firstRes = await agent.get('/auth/status');
    const tokenBefore = cookieFromResponse(firstRes, 'XSRF-TOKEN');
    expect(tokenBefore).toBeTruthy();

    const logoutRes = await agent
      .post('/auth/logout')
      .set('X-XSRF-TOKEN', tokenBefore!);

    expect(logoutRes.status).toBe(200);
    const tokenAfter = cookieFromResponse(logoutRes, 'XSRF-TOKEN');
    expect(tokenAfter).toBeTruthy();
    expect(tokenAfter).not.toBe(tokenBefore);
  });
});

describe('POST /auth/logout', () => {
  let app: ReturnType<typeof createApp>;

  beforeEach(() => {
    getTokenMock.mockReset();
    getTokenMock.mockResolvedValue({ tokens: { access_token: 'test-access-token' } });
    app = createApp();
  });

  it('destroys the session and explicitly clears the session cookie', async () => {
    // Log in first so a real session cookie exists. The XSRF token is
    // rotated on login, so use the post-login token for the logout request.
    const agent = request.agent(app);
    const startRes = await agent.get('/auth/start');
    const state = new URL(startRes.headers['location']).searchParams.get('state')!;
    const callbackRes = await agent.get('/auth/callback').query({ code: 'some-code', state });
    const xsrfToken = cookieFromResponse(callbackRes, 'XSRF-TOKEN')!;

    const logoutRes = await agent.post('/auth/logout').set('X-XSRF-TOKEN', xsrfToken);

    expect(logoutRes.status).toBe(200);
    expect(logoutRes.body).toEqual({ success: true });

    // clearCookie sends connect.sid with an epoch expiry.
    const setCookies = ([] as string[]).concat(logoutRes.headers['set-cookie'] ?? []);
    const sessionClear = setCookies.find((c) => c.startsWith('connect.sid='));
    expect(sessionClear).toBeDefined();
    expect(sessionClear).toContain('Expires=Thu, 01 Jan 1970');

    // Session is gone server-side too.
    const status = await agent.get('/auth/status');
    expect(status.body).toEqual({ authenticated: false });
  });
});
